Test: true

Welcome: true
List: true

AutoDelete: true
AntiSpam: true

Tickets: true

in:
  Test: Tools.Test

  Welcome: Tools.App.Welcome
  List: Tools.App.List

  AutoDelete: Tools.Admin.Auto.AutoDelete
  AntiSpam: Tools.Admin.Auto.AntiSpam

  Tickets: Tools.Admin.Tickets.Tickets
