Welcome: true
List: false

# AutoMod: false
AutoDelete: false
AntiSpam: false

Logs: false

Tickets: false

# Channels: false

# Messages: false

# Temp: false

in:
  Welcome: Tools/App/Welcome.py
  List: Tools/App/List.py

  # AutoMod: Tools/Admin/Auto/AutoMod.py
  AutoDelete: Tools/Admin/Auto/AutoDelete.py
  AntiSpam: Tools/Admin/Auto/AntiSpam.py

  Logs: Tools/Admin/Logs/Logs.py

  Tickets: Tools/Admin/Tickets/Tickets.py

  # Channels: Tools/Admin/Channels/Channels.py
  # Messages: Tools/Admin/Messages/Messages.py

  # Temp: Tools/Temp/Temp.py
