Tools:
  App:
    Welcome: false
    List: false

  Admin:
    #AutoMod: false # das richtet automatisch die discord Sicherheitssystem ein
    AutoDelete: false

    #AntiSpam: false

    Logs: false

    Tickets: false

    #Channels:
    #  save: false
    #  Load: false

    #  Backups: false
#  Messages:
#    YouTube: false
#    Twitch: false
#    Tiktok: false

#  Temp:
#    Voice: false
#    Text: false
